# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/report.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Report(object):
    def setupUi(self, Report):
        Report.setObjectName("Report")
        Report.resize(693, 678)
        self.buttonBox = QtWidgets.QDialogButtonBox(Report)
        self.buttonBox.setGeometry(QtCore.QRect(340, 640, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.lbl_updated = QtWidgets.QLabel(Report)
        self.lbl_updated.setGeometry(QtCore.QRect(10, 80, 671, 20))
        self.lbl_updated.setObjectName("lbl_updated")
        self.lbl_title = QtWidgets.QLabel(Report)
        self.lbl_title.setGeometry(QtCore.QRect(10, 20, 351, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_title.setFont(font)
        self.lbl_title.setObjectName("lbl_title")
        self.verticalLayoutWidget = QtWidgets.QWidget(Report)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 110, 671, 521))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.lbl_notmatched = QtWidgets.QLabel(self.tab)
        self.lbl_notmatched.setGeometry(QtCore.QRect(10, 10, 641, 20))
        self.lbl_notmatched.setObjectName("lbl_notmatched")
        self.lst_notmatched = QtWidgets.QListWidget(self.tab)
        self.lst_notmatched.setGeometry(QtCore.QRect(-1, 40, 671, 451))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lst_notmatched.sizePolicy().hasHeightForWidth())
        self.lst_notmatched.setSizePolicy(sizePolicy)
        self.lst_notmatched.setObjectName("lst_notmatched")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.lst_notfound = QtWidgets.QListWidget(self.tab_2)
        self.lst_notfound.setGeometry(QtCore.QRect(-1, 40, 671, 451))
        self.lst_notfound.setObjectName("lst_notfound")
        self.lbl_notfound = QtWidgets.QLabel(self.tab_2)
        self.lbl_notfound.setGeometry(QtCore.QRect(10, 10, 651, 20))
        self.lbl_notfound.setObjectName("lbl_notfound")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.lst_notupdated = QtWidgets.QListWidget(self.tab_5)
        self.lst_notupdated.setGeometry(QtCore.QRect(-1, 40, 661, 441))
        self.lst_notupdated.setObjectName("lst_notupdated")
        self.lbl_notfound_2 = QtWidgets.QLabel(self.tab_5)
        self.lbl_notfound_2.setGeometry(QtCore.QRect(10, 10, 631, 20))
        self.lbl_notfound_2.setObjectName("lbl_notfound_2")
        self.tabWidget.addTab(self.tab_5, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Report)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(Report.accept)
        self.buttonBox.rejected.connect(Report.reject)
        QtCore.QMetaObject.connectSlotsByName(Report)

    def retranslateUi(self, Report):
        _translate = QtCore.QCoreApplication.translate
        self.lbl_updated.setText(_translate("Report", "XXXX productos actualizados"))
        self.lbl_title.setText(_translate("Report", "Actualizacion completada"))
        self.lbl_notmatched.setText(_translate("Report", "Los siguientes productos no coinciden con la descripcion (codigo dado de alta)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Report", "Producto con error"))
        self.lbl_notfound.setText(_translate("Report", "Los siguientes productos no se han encontrado (tal vez deba dar de alta el producto manualmente)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Report", "Codigo Inexistente"))
        self.lbl_notfound_2.setText(_translate("Report", "Los siguientes productos no han sido enviados en el listado del proveedor (consultar precio)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Report", "No actualizados"))

